name: CI
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.8, openjdk@1.11]
        scala: ["2.11", "2.12", "2.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ci-test
        env:
          TEST: ${{ matrix.scala }}
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: ./scalafmt --test
